apiVersion: v2
appVersion: 2.5.0
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.x.x
description: Helm chart for Catena-X Portal
home: https://github.com/eclipse-tractusx/portal
name: portal
sources:
- https://github.com/eclipse-tractusx/portal-frontend
- https://github.com/eclipse-tractusx/portal-frontend-registration
- https://github.com/eclipse-tractusx/portal-assets
- https://github.com/eclipse-tractusx/portal-backend
type: application
version: 2.5.0
