apiVersion: v2
appVersion: 0.6.0
dependencies:
- condition: enableKeycloak
  name: keycloak
  repository: https://charts.bitnami.com/bitnami
  version: 13.3.0
description: Helm Chart for the Catena-X Semantic Hub Application
home: https://eclipse-tractusx.github.io/
name: semantic-hub
sources:
- https://github.com/eclipse-tractusx/sldt-semantic-hub
type: application
version: 0.5.0
