apiVersion: v2
appVersion: 25.0.6
dependencies:
- name: keycloak
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  version: 23.0.0
description: Helm chart for Shared Keycloak Instance
home: https://github.com/eclipse-tractusx/portal-iam
name: sharedidp
sources:
- https://github.com/eclipse-tractusx/portal-iam
type: application
version: 4.2.0
