apiVersion: v2
appVersion: 0.0.5
dependencies:
- condition: keycloak.enabled
  name: centralidp
  repository: https://eclipse-tractusx.github.io/charts/dev
  version: 3.0.0
description: 'A Helm chart to deploy SSI DIM wallet stub in kubernetes cluster '
home: https://github.com/eclipse-tractusx/ssi-dim-wallet-stub/tree/main/charts/ssi-dim-wallet-stub
name: ssi-dim-wallet-stub
sources:
- https://github.com/eclipse-tractusx/ssi-dim-wallet-stub/tree/main/charts/ssi-dim-wallet-stub
type: application
version: 0.1.8
