apiVersion: v2
appVersion: 7.0.0
dependencies:
- alias: bpdm-gate
  condition: bpdm-gate.enabled
  name: bpdm-gate
  repository: ""
  version: 7.0.0
- alias: bpdm-pool
  condition: bpdm-pool.enabled
  name: bpdm-pool
  repository: ""
  version: 8.0.0
- alias: bpdm-cleaning-service-dummy
  condition: bpdm-cleaning-service-dummy.enabled
  name: bpdm-cleaning-service-dummy
  repository: ""
  version: 4.0.0
- alias: bpdm-orchestrator
  condition: bpdm-orchestrator.enabled
  name: bpdm-orchestrator
  repository: ""
  version: 4.0.0
- name: bpdm-common
  repository: ""
  version: 1.0.4
- alias: postgres
  condition: postgres.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.12.10
- alias: centralidp
  condition: centralidp.enabled
  name: centralidp
  repository: https://eclipse-tractusx.github.io/charts/dev
  version: 4.0.1
description: A Helm chart for Kubernetes that deploys the BPDM applications
home: https://github.com/eclipse-tractusx/bpdm
maintainers:
- name: Nico Koprowski
- name: Sujit Karne
name: bpdm
sources:
- https://github.com/eclipse-tractusx/bpdm
type: application
version: 6.0.0
