apiVersion: v2
appVersion: 0.6.1
dependencies:
- condition: enablePostgres
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.12.10
description: Tractus-X BPN Discovery Helm Chart
home: https://eclipse-tractusx.github.io/
name: bpndiscovery
sources:
- https://github.com/eclipse-tractusx/sldt-bpn-discovery
type: application
version: 0.5.1
