apiVersion: v2
appVersion: 0.7.0
dependencies:
- condition: enablePostgres
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.12.10
- condition: enableKeycloak
  name: keycloak
  repository: https://charts.bitnami.com/bitnami
  version: 16.1.7
description: Tractus-X Digital Twin Registry Helm Chart
home: https://eclipse-tractusx.github.io/
name: digital-twin-registry
sources:
- https://github.com/eclipse-tractusx/sldt-digital-twin-registry
type: application
version: 0.7.0
